apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: python4j 
  janus-idp.io/tekton: python4j
  backstage.io/kubernetes-id: python4j
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python4j
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  