apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python4j-gitops
  description: This is GitOps manifest for python4j   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: python4j
    janus-idp.io/tekton: python4j 
    backstage.io/kubernetes-id: python4j 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:python4j
