apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python4j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python4j 
  name: python4j
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python4j 
